import type { Metadata } from "next";
import { Roboto, Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/Header";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  weight: ["600", "700"],
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${roboto.variable} bg-base`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
